server:
  port: 9071

spring:
  application:
    name: backend-gameserver
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@gameserver-cluster0.y9pcivx.mongodb.net/?retryWrites=true&w=majority&appName=gameserver-cluster0
