openapi: 3.0.3
info:
  title: Common Error Schema
  description: Reusable error schema for all APIs
  version: 1.0.0

paths: {}

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
          example: [ "VALIDATION_ERROR", "NOT_FOUND", "UNAUTHORIZED", "INTERNAL_ERROR" ]
        message:
          type: string
          description: Error message
          example: [ "The provided data is invalid" ]
        details:
          type: array
          items:
            type: string
          description: Detailed error information
          example: [ [ "Name cannot be empty", "Price must be greater than 0" ] ]
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: [ "2024-01-15T10:30:00Z" ]
        path:
          type: string
          description: API path where the error occurred
          example: [ "/api/v1/items" ]
        requestId:
          type: string
          format: uuid
          description: Unique request ID for debugging
          example: [ "123e4567-e89b-12d3-a456-426614174000" ]
      example:
        code: "400"
        message: "Invalid Request"
        details: "Wrong Number"
        path: "/api/v1/items"
        requestId: "123e4567-e89b-12d3-a456-426614174000"
        timestamp: "2024-01-15T10:30:00Z"